### ISSUE TITLE
Error just after input `nil` to the list.

### ISSUE THREAD

**Issue by fernandodemorais-jf** [conao3/leaf-manager.el#11]
Hello!

When I try to use `leaf-manager`, after selecting the packages and input `nil`, the following error (if I try to insert dashboard package, for example) is shown in the minibuffer:

```emacs-lisp
List contains a loop: (:url "https://github.com/emacs-dashboard/emacs-dashboard" :added "2021-07-02" :url "https://github.com/emacs-dashboard/emacs-dashboard" :added "2021-07-02" :url "https://github.com/emacs-dashboard/emacs-dashboard" . #5)
```

Thanks!

**Comment by fernandodemorais-jf** [comment]
Hello @conao3!

Sorry to insist with another comment in this issue, but this error turns `leaf-manager` unusable...

I've been trying to investigate the cause of the problem, but my lack of Emacs Lisp fluency has prevented me from correcting this `circular-list` error.

I would appreciate it if you could take a bit of your time to investigate the cause of this error.

Thanks!

**Comment by conao3** [comment]
I'm sorry too, for some reason, this repository is off-watched and I did not receive any notification of the issue.
Yes, I can reproduce this issue. However, I haven't had much time to fully debug it. I'll add a workaround later.

**Comment by conao3** [comment]
meged workaround. Please test again after MELPA build?

**Comment by fernandodemorais-jf** [comment]
Hello @conao3!

Unfortunately I'm still facing the `circular-list` error when using `leaf-manager`, even after the `leaf-convert` update.

Just to provide some info, follows the versions of the packages:

```emacs-lisp
"leaf          => 20210611.1550
 leaf-convert  => 20210813.1603
 leaf-keywords => 20210711.156
 leaf-manager  => 20200920.1643"
```

Thanks!

**Comment by conao3** [comment]
lol. I haven't commentout any lines!
https://github.com/conao3/leaf-convert.el/pull/59/files

commentout this line, circular list issue will be solved. (I will push after go to home)

**Comment by fernandodemorais-jf** [comment]
Commenting that line solved the `circular-list` error, @conao3!

Thank you for investing your time finding this solution.

---
### EDIT

I think I managed to find the problem:

- When I requested you to move the `:added` keyword to the main `leaf.el` ([this issue](https://github.com/conao3/leaf-keywords.el/issues/145)), which you did in [this merge](https://github.com/conao3/leaf.el/pull/500), the keyword remained in the `leaf-keywords` code, which caused the `circular-list` error;
- I did a test, commenting [this line](https://github.com/conao3/leaf-keywords.el/blob/f46311f8e7e5ce0d5af928fea99111b3c86de7ce/leaf-keywords.el#L87) in `leaf-keywords` and maintain [this line](https://github.com/conao3/leaf-convert.el/pull/59/files) without a comment in `leaf-convert`: `leaf-manager` worked as always, and with `:added` keyword in its buffer. :raised_hands:

Thanks!

**Comment by conao3** [comment]
Thanks for the additional investigating! I have merged two PRs. Please try after MELPA build.

**Comment by fernandodemorais-jf** [comment]
Hello @conao3,

Worked as expected.

Regards!

**Comment by conao3** [comment]
Yes! And thanks for your cooperation!
